[package]
name = "language_server_example"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
wit-bindgen = { version = "0.18.0" }

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
target = { path = "../../wit" }
